
###
GET http://localhost:8000/api/v1/accounts/
###
POST http://localhost:8000/api/v1/accounts/ HTTP/1.1
content-type: application/json

{
  "customer_id": "60d7955d6512c935b5e8d81c",
  "account_type": "sd",
  "amount": 23424.23
}

###
DELETE http://localhost:8000/api/v1/accounts/60d8abc2b293f6ae68356da0
content-type: application/json