GET http://localhost:8000/customers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJCYW5rIiwic3ViIjoiU3lzdGVtQXBwIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDAwIiwiZXhwIjoxNjI0ODk1MjA4LCJuYmYiOjE2MjQ4OTY0MDgsImlhdCI6MTYyNDg5NDYwOCwianRpIjoiYXV0aC1zZXJ2ZXItMSIsIlVzZXJuYW1lIjoia2FsaXgiLCJSb2xlIjoiQkFTSUMifQ.qM-ThytWubdfAdq_BKd6F50tZeYV4LtZ7OcK6Mrwl3E
###
GET http://localhost:8000/customers/60d7955d6512c935b5e8d81c
###
POST http://localhost:8000/customers/ HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "city": "sd",
  "zip_code": "23424",
  "date_of_birth": "2020-02-09"
}

###
DELETE http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc
content-type: application/json

###
PATCH http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc/status
content-type: application/json

{
  "status": "active"
}

