GET http://localhost:8000/customers/
###
GET http://localhost:8000/customers/60d7955d6512c935b5e8d81c
###
POST http://localhost:8000/customers/ HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "city": "sd",
  "zip_code": "23424",
  "date_of_birth": "2020-02-09"
}

###
DELETE http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc
content-type: application/json

###
PATCH http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc/status
content-type: application/json

{
  "status": "active"
}



###
GET http://localhost:8000/accounts/
###
POST http://localhost:8000/accounts/ HTTP/1.1
content-type: application/json

{
  "customer_id": "60d7955d6512c935b5e8d81c",
  "account_type": "sd",
  "amount": 23424.23
}