GET http://localhost:8000/customers

###
POST http://localhost:8000/customers HTTP/1.1
content-type: application/json

{
  "name": "sample",
  "city": "sd",
  "zip_code": "23424",
  "date_of_birth": "2020-02-09"
}

###
DELETE http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc
content-type: application/json

###
PATCH http://localhost:8000/customers/60d7c9a95ef90f972b2c52dc/status
content-type: application/json

{
  "status": "active"
}